project_id = "utfexhdncajccdpvquky"

[functions.check-milestone-unlocks]
verify_jwt = false

[functions.generate-stamp-image]
verify_jwt = false

[functions.send-stamp-email]
verify_jwt = false

[functions.generate-all-stamps]
verify_jwt = false

[functions.generate-challenge-images]
verify_jwt = false

[functions.legacy-guide]
verify_jwt = false

[functions.generate-milestone-audio]
verify_jwt = false

[functions.generate-all-milestone-audio]
verify_jwt = false

[functions.redeem-reward-code]
verify_jwt = false
