UPDATE public.milestones SET historical_event = 'Benjamin Banneker was born free in 1731 in Baltimore County Maryland, the grandson of Molly Welsh — an English servant woman who purchased and freed two enslaved men, one of whom became his grandfather. Born into freedom in a land where most who looked like him were not, he grew up on a tobacco farm his family owned outright. He carried that inheritance quietly, and it shaped everything that followed.' WHERE id = 'ac62a8cf-1815-47e7-a460-6ee9508d69bb';

UPDATE public.milestones SET historical_event = 'As a young man Banneker borrowed a pocket watch, dismantled it completely, and from memory carved a fully functioning wooden clock — every gear and mechanism reproduced by hand. It kept perfect time for decades and became known throughout the region, drawing visitors who could not believe what one self-taught man had built. He never patented it, never profited from it — he simply made it because he could.' WHERE id = '323a7c24-12e5-4e1b-b99d-fc15d768e128';

UPDATE public.milestones SET historical_event = 'At 57 years old — an age when most men of his era had long stopped learning — Banneker''s neighbor George Ellicott lent him books on astronomy, a telescope, and a set of drafting tools. He had no formal training, no teacher, no classroom — only the books, the night sky, and his own relentless mind. Within months he was calculating solar eclipses and predicting celestial events with an accuracy that stunned professional astronomers.' WHERE id = 'f187f7ea-a5e5-4e56-87c9-0e946304eb86';

UPDATE public.milestones SET historical_event = 'In 1791 Banneker was appointed to the survey team tasked with mapping the new Federal City — what would become Washington DC. When lead architect Pierre Charles L''Enfant abruptly quit and took the plans with him, Banneker is reported to have reconstructed the entire city layout from memory, saving the project. He spent weeks in the field at 60 years old, a Black man helping to design the capital of a republic that had not yet decided what to do with people like him.' WHERE id = 'b6f45363-416d-422a-ae8e-78b383645196';

UPDATE public.milestones SET historical_event = 'From 1792 to 1797 Banneker published annual almanacs containing weather forecasts, astronomical data, tide tables, and medical remedies — distributed across the colonies and into Europe. They made him one of the most widely read Black authors in early American history, and abolitionists used them as direct evidence against the claim that African people were intellectually inferior. He wrote them alone, on his farm, by candlelight, every year without fail.' WHERE id = '574e5cb8-0000-0000-0000-000000000000';

UPDATE public.milestones SET historical_event = 'In 1791 Banneker wrote directly to Thomas Jefferson — the man who authored ''all men are created equal'' while enslaving over 600 people — demanding he reconcile those words with the reality of slavery. Jefferson replied politely, forwarded the almanac to the Royal Academy of Sciences in Paris, and changed nothing. Banneker''s letter still exists, Jefferson''s contradiction still echoes, and the question he asked has never fully been answered.' WHERE challenge_id = 'bcb2ecad-853b-4df4-a7ca-c2d881307125' AND order_index = 6;

UPDATE public.milestones SET historical_event = 'From 1792 to 1797 Banneker published annual almanacs containing weather forecasts, astronomical data, tide tables, and medical remedies — distributed across the colonies and into Europe. They made him one of the most widely read Black authors in early American history, and abolitionists used them as direct evidence against the claim that African people were intellectually inferior. He wrote them alone, on his farm, by candlelight, every year without fail.' WHERE challenge_id = 'bcb2ecad-853b-4df4-a7ca-c2d881307125' AND order_index = 5;